preserve_hierarchy: true
files:
  - source: /apps/web/messages/en.json
    translation: /apps/web/messages/%two_letters_code%.json
    type: json
    languages_mapping:
      two_letters_code:
        ar: ar
