import { StaffRole } from '@prisma/client';

export const STAFF_PERMISSIONS = [
  'companies.read',
  'branches.read',
  'tables.read',
  'sessions.read',
  'sessions.manage',
  'menu.read',
  'menu.manage',
  'menu.manage_categories',
  'menu.manage_items',
  'menu.manage_modifiers',
  'menu.manage_branch_overrides',
  'media.read',
  'media.manage',
  'experience.read',
  'experience.manage',
  'content.read',
  'content.manage',
  'venue_zones.read',
  'venue_zones.manage',
  'cart.read',
  'orders.read',
  'orders.cashier_review',
  'orders.accept',
  'orders.reject',
  'orders.serve',
  'orders.complete',
  'bills.read',
  'bills.request',
  'bills.acknowledge',
  'bills.present',
  'bills.pay',
  'bills.close',
  'bills.cancel',
  'ai_waiter.read',
  'ai_waiter.manage',
  'ai_waiter.escalate',
  'ai_waiter.usage.read',
  'smart_cashier.read',
  'smart_cashier.manage',
  'smart_cashier.evaluate',
  'smart_cashier.auto_accept',
  'preparation.read',
  'preparation.start',
  'preparation.ready',
  'preparation.cancel',
  'waiter_calls.read',
  'waiter_calls.acknowledge',
  'waiter_calls.resolve',
  'waiter_calls.cancel',
  'notifications.read',
  'presence.read',
  'staff.read',
  'staff.manage',
  'settings.read',
  'settings.manage',
  'feature_flags.read',
  'feature_flags.manage',
  'autopilot.read',
  'autopilot.manage',
  'analytics.read',
  'audit.read',
  'auth.read',
  'auth.manage',
  'system.jobs.read',
  'system.jobs.manage',
  'system.docs.read',
  'security.read',
  'security.manage',
] as const;

export type StaffPermission = (typeof STAFF_PERMISSIONS)[number];

export const STAFF_PERMISSION_SET = new Set<string>(STAFF_PERMISSIONS);

export const ROLE_PERMISSIONS: Record<StaffRole, readonly StaffPermission[]> = {
  [StaffRole.owner]: STAFF_PERMISSIONS,
  [StaffRole.branch_manager]: [
    'companies.read',
    'branches.read',
    'tables.read',
    'sessions.read',
    'sessions.manage',
    'menu.read',
    'menu.manage',
    'menu.manage_categories',
    'menu.manage_items',
    'menu.manage_modifiers',
    'menu.manage_branch_overrides',
    'media.read',
    'media.manage',
    'experience.read',
    'experience.manage',
    'content.read',
    'content.manage',
    'venue_zones.read',
    'venue_zones.manage',
    'cart.read',
    'orders.read',
    'orders.cashier_review',
    'orders.accept',
    'orders.reject',
    'orders.serve',
    'orders.complete',
    'bills.read',
    'bills.request',
    'bills.acknowledge',
    'bills.present',
    'bills.pay',
    'bills.close',
    'bills.cancel',
    'ai_waiter.read',
    'ai_waiter.manage',
    'ai_waiter.escalate',
    'ai_waiter.usage.read',
    'smart_cashier.read',
    'smart_cashier.manage',
    'smart_cashier.evaluate',
    'smart_cashier.auto_accept',
    'preparation.read',
    'preparation.start',
    'preparation.ready',
    'preparation.cancel',
    'waiter_calls.read',
    'waiter_calls.acknowledge',
    'waiter_calls.resolve',
    'waiter_calls.cancel',
    'notifications.read',
    'presence.read',
    'staff.read',
    'settings.read',
    'settings.manage',
    'feature_flags.read',
    'feature_flags.manage',
    'autopilot.read',
    'autopilot.manage',
    'analytics.read',
    'audit.read',
    'auth.read',
    'system.jobs.read',
    'system.docs.read',
    'security.read',
  ],
  [StaffRole.cashier]: [
    'menu.read',
    'media.read',
    'experience.read',
    'content.read',
    'venue_zones.read',
    'orders.read',
    'orders.cashier_review',
    'orders.accept',
    'orders.reject',
    'orders.complete',
    'bills.read',
    'bills.acknowledge',
    'bills.present',
    'bills.pay',
    'bills.close',
    'bills.cancel',
    'smart_cashier.read',
    'smart_cashier.evaluate',
    'smart_cashier.auto_accept',
    'tables.read',
    'sessions.read',
    'orders.serve',
    'bills.request',
    'ai_waiter.read',
    'waiter_calls.read',
    'settings.read',
    'autopilot.read',
    'analytics.read',
  ],
  [StaffRole.waiter]: [
    'menu.read',
    'media.read',
    'experience.read',
    'content.read',
    'venue_zones.read',
    'tables.read',
    'sessions.read',
    'ai_waiter.read',
    'ai_waiter.escalate',
    'orders.serve',
    'waiter_calls.read',
    'waiter_calls.acknowledge',
    'waiter_calls.resolve',
    'waiter_calls.cancel',
    'notifications.read',
    'autopilot.read',
    'autopilot.manage',
  ],
  [StaffRole.kitchen]: [
    'menu.read',
    'media.read',
    'experience.read',
    'content.read',
    'venue_zones.read',
    'ai_waiter.read',
    'preparation.read',
    'preparation.start',
    'preparation.ready',
    'preparation.cancel',
    'autopilot.read',
  ],
  [StaffRole.barista]: [
    'menu.read',
    'media.read',
    'experience.read',
    'content.read',
    'venue_zones.read',
    'ai_waiter.read',
    'preparation.read',
    'preparation.start',
    'preparation.ready',
    'preparation.cancel',
    'autopilot.read',
  ],
  [StaffRole.menu_admin]: [
    'companies.read',
    'branches.read',
    'menu.read',
    'menu.manage',
    'menu.manage_categories',
    'menu.manage_items',
    'menu.manage_modifiers',
    'menu.manage_branch_overrides',
    'media.read',
    'media.manage',
    'experience.read',
    'content.read',
    'content.manage',
    'venue_zones.read',
    'venue_zones.manage',
    'ai_waiter.read',
    'settings.read',
    'analytics.read',
  ],
};

export function isStaffPermission(value: string): value is StaffPermission {
  return STAFF_PERMISSION_SET.has(value);
}

export function getRolePermissions(
  role: StaffRole,
): readonly StaffPermission[] {
  return ROLE_PERMISSIONS[role];
}
